import type { Metadata } from "next";
// import { ThemeProvider } from "next-themes";
import ThemeProvider from "./theme-provider";

import Footer from "@/components/navigation/footer";
import Navbar from "@/components/navigation/navbar";

import GoogleAnalytics from "../components/analytics/GoogleAnalytics";

import { Inter } from "next/font/google";

import "../styles/globals.css";
import "../styles/prism-dracula.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Blog | ${process.env.NEXT_PUBLIC_OWNER_NAME}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics />

      <body className="bg-white dark:bg-slate-900">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />

          <main className="min-h-[94%] py-24 pb-20 mt-28">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
